name: Generate README
on:
  push:
    branches:
      - main
    paths:
      - 'datasets/**/*.yml'
      - 'datasets/**/*.yaml'
      - 'README_template.md'
      - 'scripts/*'
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate YAML files
        run: python scripts/validate_yaml.py

      - name: Generate README
        run: python scripts/generate_readme.py

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet README.md; then
            echo "No changes to README.md"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in README.md"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Stage README changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update README after merge to main"
          title: "docs: update README after merge to main"
          body: |
            This PR automatically updates the README.md based on merged dataset changes.
            
            Changes were detected in the main branch that affect the README content.
          branch: readme-update-after-merge
          base: main
          delete-branch: true
          labels: |
            documentation
            automated-pr