name: Generate README

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  # Checkout the PR branch
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate YAML files
        run: python scripts/validate_yaml.py

      - name: Generate README
        run: python scripts/generate_readme.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README" || echo "No changes to commit"
          git push origin ${{ github.head_ref }}