name: Validate PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate YAML files
        run: python scripts/validate_yaml.py

      - name: Test generating README
        run: python scripts/generate_readme.py
